name: build

on:
  push:
    branches:
      - main
jobs:
  makedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step1 - Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Step2 - Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: StepX - Make userguide
        run: |
          sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng
          make html
      - name: Step 3 - Save user-guide build /tmp
        run: |
          mkdir /tmp/gh-pages
          cp -r build/html/* /tmp/gh-pages
          pwd
          ls -a
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Step 4 Commit the new html build
        run: |
          pwd
          ls -a
          git rm -rf *
          cp -r /tmp/gh-pages/* .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update" -a || true
      - name: Push changes to gh-page branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
